knpu_oauth2_client:
    clients:
        azure_main:
            type: azure
            client_id: '%env(AZURE_ID)%'
            client_secret: '%env(AZURE_SECRET)%'
            redirect_route: connect_azure_check
            redirect_params: {}
            default_end_point_version: '2.0'
