knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(AZURE_ID)%'
            client_secret: '%env(AZURE_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: azure
            default_end_point_version: '2.0'
